[package]
name = "brewthink-host"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
anyhow = "1"
regex = "1"
rustc-demangle = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.10"
toml = "0.8"
tar = "0.4"
flate2 = "1"

[dev-dependencies]
libc = "0.2"
tempfile = "3"
crc32fast = "=1.5.0"
